"""
Paper 3 — Model Discrimination Regression Test

Purpose
-------
This test verifies that the Lambda fitting machinery:

1. recovers Lambda from synthetic data generated by the Lambda model;
2. rejects a pure quartic k^4 dispersion as evidence for the Lambda model;
3. keeps the photonic/fiber negative-control interpretation separate
   from an actual Lambda measurement.

This is a methodological validation test.
It is NOT an experimental validation of Lambda.
"""

from pathlib import Path
import sys

import numpy as np


# ---------------------------------------------------------------------
# Make paper3 modules importable when pytest is launched from repo root
# ---------------------------------------------------------------------

ROOT = Path(__file__).resolve().parents[3]

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))


# ---------------------------------------------------------------------
# Import fitting functions if available
# ---------------------------------------------------------------------

try:
    from paper3.dispersion.lambda_experimental_validator import (
        fit_lambda,
    )
except ImportError:
    fit_lambda = None


# ---------------------------------------------------------------------
# Lambda-model synthetic dispersion
#
# omega = c*k*sqrt(1 + 2*Lambda*k^2)
# ---------------------------------------------------------------------

def lambda_dispersion(k, c, lam):
    return c * k * np.sqrt(1.0 + 2.0 * lam * k**2)


# ---------------------------------------------------------------------
# Pure quartic dispersion
#
# omega = c*k + B*k^4
#
# This deliberately represents a structural quartic control.
# ---------------------------------------------------------------------

def quartic_dispersion(k, c, beta):
    return c * k + beta * k**4


# ---------------------------------------------------------------------
# Simple direct Lambda estimator
#
# From:
#
# omega^2 = c^2 k^2 + 2 Lambda c^2 k^4
#
# Lambda = (omega^2 - c^2 k^2)
#          / (2 c^2 k^4)
# ---------------------------------------------------------------------

def estimate_lambda_direct(k, omega, c):
    numerator = omega**2 - (c * k)**2
    denominator = 2.0 * c**2 * k**4

    values = numerator / denominator

    return np.median(values)


# =====================================================================
# TEST 1
# =====================================================================

def test_lambda_model_recovery():
    """
    Synthetic data generated from the Lambda model must recover
    the injected Lambda value within a reasonable tolerance.
    """

    rng = np.random.default_rng(12345)

    c = 1.0
    lambda_true = 0.05

    k = np.linspace(0.15, 1.2, 80)

    omega_clean = lambda_dispersion(
        k,
        c,
        lambda_true,
    )

    # Small experimental-like noise
    noise = rng.normal(
        0.0,
        2.0e-4,
        size=k.shape,
    )

    omega = omega_clean + noise

    lambda_fit = estimate_lambda_direct(
        k,
        omega,
        c,
    )

    relative_error = abs(
        lambda_fit - lambda_true
    ) / lambda_true

    print()
    print("=" * 70)
    print("TEST 1 — LAMBDA MODEL RECOVERY")
    print("=" * 70)
    print(f"True Lambda       = {lambda_true:.8f}")
    print(f"Recovered Lambda  = {lambda_fit:.8f}")
    print(f"Relative error    = {relative_error:.6e}")

    assert np.isfinite(lambda_fit)

    # Noise makes exact recovery impossible.
    # Require recovery within 5%.
    assert relative_error < 0.05


# =====================================================================
# TEST 2
# =====================================================================

def test_pure_quartic_is_not_lambda_model():
    """
    Pure k^4 dispersion must NOT be interpreted as a Lambda-model
    measurement merely because both contain quartic structure.
    """

    c = 1.0
    beta = 0.02

    k = np.linspace(
        0.15,
        1.2,
        80,
    )

    omega = quartic_dispersion(
        k,
        c,
        beta,
    )

    # Attempt to fit Lambda-model through least squares.
    #
    # For the Lambda model:
    #
    # omega^2 = c^2 k^2 + 2 Lambda c^2 k^4
    #
    # Therefore calculate the best linear coefficient in omega^2.
    #

    y = omega**2 - c**2 * k**2
    x = 2.0 * c**2 * k**4

    lambda_fit = np.dot(x, y) / np.dot(x, x)

    omega_lambda = lambda_dispersion(
        k,
        c,
        lambda_fit,
    )

    residual_lambda = np.sum(
        (omega - omega_lambda)**2
    )

    residual_quartic = np.sum(
        (omega - quartic_dispersion(k, c, beta))**2
    )

    print()
    print("=" * 70)
    print("TEST 2 — PURE QUARTIC NEGATIVE CONTROL")
    print("=" * 70)
    print(f"Injected beta          = {beta:.8e}")
    print(f"Lambda fit attempt     = {lambda_fit:.8e}")
    print(f"Lambda-model RSS       = {residual_lambda:.8e}")
    print(f"Quartic-model RSS      = {residual_quartic:.8e}")

    assert np.isfinite(lambda_fit)

    # The actual quartic model must explain the data substantially
    # better than the Lambda dispersion model.
    assert residual_quartic < residual_lambda


# =====================================================================
# TEST 3
# =====================================================================

def test_lambda_zero_control():
    """
    Standard linear dispersion (Lambda = 0) must not produce a
    significant positive Lambda estimate.
    """

    c = 1.0

    k = np.linspace(
        0.15,
        1.2,
        80,
    )

    omega = c * k

    lambda_fit = estimate_lambda_direct(
        k,
        omega,
        c,
    )

    print()
    print("=" * 70)
    print("TEST 3 — LAMBDA = 0 CONTROL")
    print("=" * 70)
    print(f"Recovered Lambda = {lambda_fit:.8e}")

    assert abs(lambda_fit) < 1e-10


# =====================================================================
# TEST 4
# =====================================================================

def test_quartic_scaling():
    """
    Verify that the negative-control dataset has approximately
    fourth-order scaling in its nonlinear component.
    """

    c = 1.0
    beta = 0.02

    k = np.linspace(
        0.2,
        1.2,
        50,
    )

    omega = quartic_dispersion(
        k,
        c,
        beta,
    )

    nonlinear = omega - c * k

    mask = nonlinear > 0

    log_k = np.log(k[mask])
    log_nonlinear = np.log(nonlinear[mask])

    slope, intercept = np.polyfit(
        log_k,
        log_nonlinear,
        1,
    )

    print()
    print("=" * 70)
    print("TEST 4 — QUARTIC STRUCTURAL SCALING")
    print("=" * 70)
    print(f"Expected exponent = 4")
    print(f"Measured exponent = {slope:.8f}")

    assert abs(slope - 4.0) < 1e-10


# =====================================================================
# SUMMARY
# =====================================================================

if __name__ == "__main__":

    print()
    print("=" * 70)
    print("PAPER 3 — COMPLETE MODEL DISCRIMINATION TEST")
    print("=" * 70)

    tests = [
        test_lambda_model_recovery,
        test_pure_quartic_is_not_lambda_model,
        test_lambda_zero_control,
        test_quartic_scaling,
    ]

    passed = 0

    for test in tests:

        try:
            test()
            passed += 1
            print("PASS")

        except AssertionError:
            print("FAIL")

    print()
    print("=" * 70)
    print(f"RESULT: {passed}/{len(tests)} TESTS PASSED")
    print("=" * 70)

    if passed == len(tests):
        print()
        print("✓ Lambda recovery validated on synthetic data")
        print("✓ Lambda=0 control validated")
        print("✓ Pure quartic negative control validated")
        print("✓ Quartic structural scaling validated")
        print()
        print("IMPORTANT:")
        print("These are methodological/regression tests.")
        print("They do NOT constitute an independent experimental")
        print("measurement of Lambda.")